### ISSUE TITLE
CrewLink does not work with itchio version of Among Us

### ISSUE THREAD

**Issue by sanjitpush** [ottomated/CrewLink#44]
I am getting the following error whenever I launch my itchio version of among us while CrewLink is running

```
Uncaught Exception:
Error: Cannot create a string longer than 0x 1fffffe8 characters
   at Object.slice (buffer.js:585:37)
   at Uint8Array.toString (buffer.js:782:14)
   at GamerReader_GameReader.readString
(C:\Users\sanji\AppData\Local\Programs\crwelink\resources\app.asar\webpack:\src\m...:17)
    at GameReader_GameReader.parsePlayer
(C:\Users\sanji\AppData\Local\Programs\crwelink\resources\app.asar\webpack:\src\m...:15)
    at GameReader_GameReader.loop
(C:\Users\sanji\AppData\Local\Programs\crwelink\resources\app.asar\webpack:\src\m...:23)
    at Timeout.frame [as_onTimeout]
(C:\Users\sanji\AppData\Local\Programs\crwelink\resources\app.asar\webpack:\src\m...:15)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

Any idea how I could fix this? Thank you.

**Comment by uzervlad** [comment]
Duplicate of #14?

**Comment by jackschedel** [comment]
Duplicate of #14

**Comment by sanjitpush** [comment]
Looks like it is, thanks for the quick response. I'll use that to address the issue I'm having.
